-- Rate limit information

create table twitter_api_rate_limits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,

  twitter_id bigint references twitter_profiles not null,
  endpoint text not null check (endpoint in ('lookup-tweets', 'lookup-users', 'search-tweets')),
  
  resets_at timestamp with time zone not null,
  deleted boolean default false not null
);

alter table twitter_api_rate_limits enable row level security;
