create table user_campaign (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    user_id uuid references auth.users not null,
    queries jsonb not null,

    deleted boolean not null default false
);

create table tweet_campaign (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    user_id uuid references auth.users not null,
    queries jsonb not null,

    deleted boolean not null default false
);
