create table user_campaigns (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    user_id uuid references auth.users not null,
    keywords text[] not null,
    entities bigint[] not null,

    paused boolean not null default false,
    deleted boolean not null default false
);
