create table profile_campaigns (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    user_id uuid references auth.users not null,
    keywords text[] not null,
    entities bigint[] not null,

    paused boolean not null default false,
    deleted boolean not null default false
);

create trigger on_profile_campaigns_updated
  before update on profile_campaigns
  for each row execute procedure set_updated_at();

alter table profile_campaigns enable row level security;
