-- Twitter lists and list membership

create table if not exists twitter_list (
  id bigint primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,

  list_created_at timestamp with time zone not null,
  owner_id bigint references twitter_profile not null,
  name text not null,
  description text not null,
  followers_count integer not null,
  members_count integer not null,
  private boolean not null,

  -- For internal delete logic
  to_delete boolean not null default false
);

alter table twitter_list enable row level security;

create policy "Users can view their own Twitter lists."
    on twitter_list for select
    to authenticated
    using (
      auth.uid() in (
      select user_profile.id from user_profile
      where user_profile.twitter_id = twitter_list.owner_id
    ));

create policy "Users can insert their own Twitter lists."
    on twitter_list for insert
    to authenticated
    with check (
      auth.uid() in (
      select user_profile.id from user_profile
      where user_profile.twitter_id = twitter_list.owner_id
    ));

create policy "Users can update their own Twitter lists."
    on twitter_list for update
    to authenticated
    using (
      auth.uid() in (
      select user_profile.id from user_profile
      where user_profile.twitter_id = twitter_list.owner_id
    ));

create policy "Users can delete their own Twitter lists."
    on twitter_list for delete
    to authenticated
    using (
      auth.uid() in (
      select user_profile.id from user_profile
      where user_profile.twitter_id = twitter_list.owner_id
    ));

create table if not exists twitter_list_member (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    
    list_id bigint references twitter_list not null,
    member_id bigint references twitter_profile not null,

    -- For internal delete logic
    to_delete boolean not null default false
);

alter table twitter_list_member enable row level security;
